### PR TITLE
improve the documentation and remove all wrong things and error codes…

### PR DESCRIPTION
**Pull request by dev-aditya-lab**
….    - make more efficient  - improve readability - add missing concepts (only basics js or important things not advanced js)

improve the documentation and remove all wrong things and error codes.  

- make more efficient 
- improve readability
- add missing concepts (only basics js or important things not advanced js)

### CODE REVIEW

**Comment by sanskaarz** [comment]
Hey @dev-aditya-lab,
You have raised 2 PRs,
Could you tell me which one I should merge?

**Comment by dev-aditya-lab** [comment]
Last one

**Comment by sanskaarz** [comment]
Ohkk, That's why merging the last PR is making conflicts because I've, merged the last second one.
I'm reverting the last-second one.

**Comment by sanskaarz** [comment]
I've merged the PR successfully @dev-aditya-lab.
Thanks for the fantastic improvements! This is a great start, and it definitely makes the file much clearer and more informative for other users. I especially appreciate your initiative in tackling this.

**Comment by sanskaarz** [comment]
Let me know if you have more ideas for the README or want to contribute further!
I also hope that you consider starring this repository so that it can reach more developers looking to get into open-source. 🚀💜

**Review by sanskaarz — APPROVED** [review]

**Pull request merged**
